export const GET_POST_LIST_REQUEST = "GET_POST_LIST_REQUEST";
export const GET_POST_LIST_SUCCESS = "GET_POST_LIST_SUCCESS";
export const GET_POST_LIST_FAIL = "GET_POST_LIST_FAIL";

export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_DATA_PAGE = "CHANGE_DATA_PAGE";
// export const FILTER_COMPLETED = "FILTER_COMPLETED";
